### ISSUE TITLE
Advanced Usage example for compare_column_values doesn't work with dbt 0.18

### ISSUE THREAD

**Issue by ededdneddyfan** [fishtown-analytics/dbt-audit-helper#28]
### Describe the bug

See above!

### Steps to reproduce

Dummy code based on our project
```sql
{%- set columns_to_compare=adapter.get_columns_in_relation(ref('fct_orders'))  -%}

{% set old_etl_relation_query %}
    select * from data.prod_schema.fct_orders
{% endset %}

{% set new_etl_relation_query %}
    select * from data.dev_schema.fct_orders
{% endset %}

{% if execute %}
    {% for column in columns_to_compare %}
        {{ log('Comparing column "' ~ column.name ~'"', info=True) }}

        {% set audit_query = audit_helper.compare_column_values(
            a_query=old_etl_relation_query,
            b_query=new_etl_relation_query,
            primary_key="FINAL_ORDER_ID",
            column_to_compare=column.name
        ) %}

        {% set audit_results = run_query(audit_query) %}
        {% do audit_results.print_table() %}
        {{ log("", info=True) }}

    {% endfor %}
{% endif %}
```

### Expected results

Can run the audit query

### Screenshots and log output

Encountered an error:
Runtime Error
  Compilation Error in model test (models/marts/test.sql)
    'audit_helper' is undefined

### System information
**The contents of your `packages.yml` file:**

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake

- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.18.1
   latest version: 0.18.1

Up to date!

Plugins:
  - bigquery: 0.18.1
  - snowflake: 0.18.1
  - redshift: 0.18.1
  - postgres: 0.18.1
```

**The operating system you're using:**

**The output of `python --version`:**

### Are you interested in contributing the fix?

Yes, let me know what the problem is with the syntax here!

**Comment by ededdneddyfan** [comment]
Think this was a PEBCAK error, I'm able to get this to run now
